#include <iostream>
using namespace std;
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.
int main() {
  int i = 1, j = 1, temp, max = 4000000;
  int ans = 0;
  while (i < max) {
    //generate fib terms from i and j
    temp = i;
    i = i + j;
    j = temp;
    if (i % 2 == 0) {
      ans += i;
    }
  }
  cout << ans << endl;
  return 0;
}
